class: uiagile
params:
  model_path: ./models/UI-AGILE-3B
  max_new_tokens: 64
  dtype: float16
  device_map: auto
  repo_id: KDEGroup/UI-AGILE-3B
  thinking: false
  max_pixels: 1003520
  quantize: true
